// OcdCoins.js
// 각 코인의 Exchange Netflow / Reserve 를 여기서 수정하세요.
const OcdCoins = [
    {
        symbol: "BTC",
        name: "Bitcoin",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [2.1, -1.4, 0.8, -3.2, 1.5, -0.6, -2.4],
        reserve: [2.71, 2.705, 2.712, 2.698, 2.715, 2.709, 2.717]
    },
    {
        symbol: "ETH",
        name: "Ethereum",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [-5.2, 1.1, -3.4, 2.8, -1.9, 0.4, -2.7],
        reserve: [15.92, 15.88, 15.85, 15.87, 15.83, 15.81, 15.82]
    },
    {
        symbol: "XRP",
        name: "XRP",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [12, -4, 8, -15, 6, 3, -7],
        reserve: [4.08, 4.09, 4.10, 4.11, 4.10, 4.12, 4.12]
    },
    {
        symbol: "USDT",
        name: "Tether",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [120, -80, 45, -30, 90, -50, 20],
        reserve: [51.8, 52.0, 51.9, 52.2, 52.1, 52.3, 52.4]
    },
    {
        symbol: "XLM",
        name: "Stellar",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [1.8, -0.9, 2.4, -1.2, 3.1, 0.5, -0.7],
        reserve: [42.1, 42.3, 41.9, 42.8, 43.2, 42.7, 43.5]
    },
    {
        symbol: "BABYDOGE",
        name: "Baby Doge Coin",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [0.5, -0.3, 1.1, -0.8, 0.9, 0.2, -0.4],
        reserve: [18.2, 18.1, 18.4, 18.0, 18.5, 18.3, 18.6]
    },
    {
        symbol: "ADA",
        name: "Cardano",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [-0.2, 0.6, -0.5, 1.0, -0.3, 0.4, 0.1],
        reserve: [9.1, 9.2, 9.0, 9.3, 9.15, 9.25, 9.4]
    },
    {
        symbol: "AVAX",
        name: "Avalanche",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [0.8, -1.0, 0.3, 1.5, -0.6, 0.9, -0.2],
        reserve: [3.4, 3.35, 3.5, 3.45, 3.6, 3.55, 3.7]
    },
    {
        symbol: "DOT",
        name: "Polkadot",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [-0.4, 0.7, -0.9, 0.5, 1.2, -0.3, 0.6],
        reserve: [1.12, 1.10, 1.15, 1.13, 1.18, 1.16, 1.20]
    },
    {
        symbol: "LINK",
        name: "Chainlink",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [0.3, -0.5, 0.9, -0.2, 1.1, 0.4, -0.7],
        reserve: [0.85, 0.84, 0.88, 0.86, 0.90, 0.89, 0.92]
    },
    {
        symbol: "SHIB",
        name: "Shiba Inu",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [0.5, -0.7, -0.9, -0.7, 0.0, 0.2, 0.1],
        reserve: [0.85, 0.74, 0.78, 0.76, 0.90, 0.89, 0.92]
    },
    {
        symbol: "BTT",
        name: "BitTorrent",
        labels: ["Jul 28","Jul 29","Jul 30","Jul 31","Aug 1","Aug 2","Aug 3"],
        netflow: [0.8, -1.0, 0.3, 1.5, -0.6, 0.9, -0.2],
        reserve: [3.4, 3.35, 3.5, 3.45, 3.6, 3.55, 3.7]
    },
    { symbol: "MATIC", name: "Polygon" },
    { symbol: "TRX", name: "TRON" },
    { symbol: "ATOM", name: "Cosmos" },
    { symbol: "UNI", name: "Uniswap" },
    { symbol: "ETC", name: "Ethereum Classic" },
    { symbol: "BCH", name: "Bitcoin Cash" },
    { symbol: "NEAR", name: "NEAR Protocol" },
    { symbol: "APT", name: "Aptos" },
    { symbol: "ARB", name: "Arbitrum" },
    { symbol: "OP", name: "Optimism" },
    { symbol: "SUI", name: "Sui" },
    { symbol: "PEPE", name: "Pepe" },
    { symbol: "WLD", name: "Worldcoin" },
    { symbol: "INJ", name: "Injective" },
    { symbol: "SEI", name: "Sei" },
    { symbol: "TIA", name: "Celestia" },
    { symbol: "BONK", name: "Bonk" },
    { symbol: "RENDER", name: "Render" },
    { symbol: "FET", name: "Fetch.ai" },
    { symbol: "IMX", name: "Immutable" },
    { symbol: "STX", name: "Stacks" },
    { symbol: "AAVE", name: "Aave" },
    { symbol: "MKR", name: "Maker" },
    { symbol: "GRT", name: "The Graph" },
    { symbol: "ALGO", name: "Algorand" },
    { symbol: "FLOW", name: "Flow" },
    { symbol: "SAND", name: "The Sandbox" },
    { symbol: "MANA", name: "Decentraland" },
    { symbol: "AXS", name: "Axie Infinity" },
    { symbol: "CHZ", name: "Chiliz" },
    { symbol: "ENJ", name: "Enjin Coin" },
    { symbol: "BAT", name: "Basic Attention Token" },
    { symbol: "ZRX", name: "0x" },
    { symbol: "QTUM", name: "Qtum" },
    { symbol: "ICX", name: "ICON" },
    { symbol: "WAVES", name: "Waves" },
    { symbol: "ONT", name: "Ontology" },
    { symbol: "ZIL", name: "Zilliqa" },
    { symbol: "IOST", name: "IOST" },
    { symbol: "VET", name: "VeChain" },
    { symbol: "THETA", name: "Theta Network" },
    { symbol: "HBAR", name: "Hedera" },
    { symbol: "EGLD", name: "MultiversX" },
    { symbol: "KAVA", name: "Kava" },
    { symbol: "CELO", name: "Celo" },
    { symbol: "ONE", name: "Harmony" },
    { symbol: "ANKR", name: "Ankr" },
    { symbol: "CRO", name: "Cronos" },
    { symbol: "KLAY", name: "Klaytn" },
    { symbol: "HOT", name: "Holo" },
    { symbol: "STEEM", name: "Steem" },
    { symbol: "SXP", name: "Solar" },
    { symbol: "ASTR", name: "Astar" },
    { symbol: "BLUR", name: "Blur" },
    { symbol: "MASK", name: "Mask Network" },
    { symbol: "LDO", name: "Lido DAO" },
    { symbol: "RPL", name: "Rocket Pool" },
    { symbol: "SSV", name: "SSV Network" },
    { symbol: "PENDLE", name: "Pendle" },
    { symbol: "JUP", name: "Jupiter" },
    { symbol: "W", name: "Wormhole" },
    { symbol: "STRK", name: "Starknet" },
    { symbol: "ZK", name: "zkSync" },
    { symbol: "PIXEL", name: "Pixels" },
    { symbol: "PORTAL", name: "Portal" },
    { symbol: "PDA", name: "PlayDapp" },
    { symbol: "MBL", name: "MovieBloc" },
    { symbol: "HIVE", name: "Hive" },
    { symbol: "MED", name: "MediBloc" },
    { symbol: "CBK", name: "Cobak Token" },
    { symbol: "META", name: "Metadium" },
    { symbol: "WEMIX", name: "WEMIX" },
    { symbol: "BORA", name: "BORA" },
    { symbol: "XEC", name: "eCash" },
    { symbol: "LSK", name: "Lisk" },
    { symbol: "POWR", name: "Powerledger" },
    { symbol: "ELF", name: "aelf" },
    { symbol: "ARK", name: "Ark" },
    { symbol: "STORJ", name: "Storj" },
    { symbol: "GLM", name: "Golem" },
    { symbol: "GAS", name: "Gas" },
    { symbol: "NEO", name: "NEO" },
    { symbol: "IOTA", name: "IOTA" },
    { symbol: "XTZ", name: "Tezos" },
    { symbol: "EOS", name: "EOS" },
    { symbol: "BSV", name: "Bitcoin SV" },
    { symbol: "BTG", name: "Bitcoin Gold" }
];

window.OcdCoins = OcdCoins;
console.log("✅ OcdCoins.js 로드 완료! 총 " + OcdCoins.length + "개 코인");
