// OcdCoins.js
// 업비트 + 빗썸 주요 상장 코인 리스트
const OcdCoins = [
    { symbol: "BTC", name: "Bitcoin" },
    { symbol: "ETH", name: "Ethereum" },
    { symbol: "XRP", name: "XRP" },
    { symbol: "USDT", name: "Tether" },
    { symbol: "SOL", name: "Solana" },
    { symbol: "DOGE", name: "Dogecoin" },
    { symbol: "ADA", name: "Cardano" },
    { symbol: "AVAX", name: "Avalanche" },
    { symbol: "DOT", name: "Polkadot" },
    { symbol: "LINK", name: "Chainlink" },
    { symbol: "MATIC", name: "Polygon" },
    { symbol: "SHIB", name: "Shiba Inu" },
    { symbol: "TRX", name: "TRON" },
    { symbol: "ATOM", name: "Cosmos" },
    { symbol: "UNI", name: "Uniswap" },
    { symbol: "ETC", name: "Ethereum Classic" },
    { symbol: "XLM", name: "Stellar" },
    { symbol: "BCH", name: "Bitcoin Cash" },
    { symbol: "NEAR", name: "NEAR Protocol" },
    { symbol: "APT", name: "Aptos" },
    { symbol: "ARB", name: "Arbitrum" },
    { symbol: "OP", name: "Optimism" },
    { symbol: "SUI", name: "Sui" },
    { symbol: "PEPE", name: "Pepe" },
    { symbol: "WLD", name: "Worldcoin" },
    { symbol: "INJ", name: "Injective" },
    { symbol: "SEI", name: "Sei" },
    { symbol: "TIA", name: "Celestia" },
    { symbol: "BONK", name: "Bonk" },
    { symbol: "RENDER", name: "Render" },
    { symbol: "FET", name: "Fetch.ai" },
    { symbol: "IMX", name: "Immutable" },
    { symbol: "STX", name: "Stacks" },
    { symbol: "AAVE", name: "Aave" },
    { symbol: "MKR", name: "Maker" },
    { symbol: "GRT", name: "The Graph" },
    { symbol: "ALGO", name: "Algorand" },
    { symbol: "FLOW", name: "Flow" },
    { symbol: "SAND", name: "The Sandbox" },
    { symbol: "MANA", name: "Decentraland" },
    { symbol: "AXS", name: "Axie Infinity" },
    { symbol: "CHZ", name: "Chiliz" },
    { symbol: "ENJ", name: "Enjin Coin" },
    { symbol: "BAT", name: "Basic Attention Token" },
    { symbol: "ZRX", name: "0x" },
    { symbol: "QTUM", name: "Qtum" },
    { symbol: "ICX", name: "ICON" },
    { symbol: "WAVES", name: "Waves" },
    { symbol: "ONT", name: "Ontology" },
    { symbol: "ZIL", name: "Zilliqa" },
    { symbol: "IOST", name: "IOST" },
    { symbol: "VET", name: "VeChain" },
    { symbol: "THETA", name: "Theta Network" },
    { symbol: "HBAR", name: "Hedera" },
    { symbol: "EGLD", name: "MultiversX" },
    { symbol: "KAVA", name: "Kava" },
    { symbol: "CELO", name: "Celo" },
    { symbol: "ONE", name: "Harmony" },
    { symbol: "ANKR", name: "Ankr" },
    { symbol: "CRO", name: "Cronos" },
    { symbol: "KLAY", name: "Klaytn" },
    { symbol: "BTT", name: "BitTorrent" },
    { symbol: "HOT", name: "Holo" },
    { symbol: "STEEM", name: "Steem" },
    { symbol: "SXP", name: "Solar" },
    { symbol: "ASTR", name: "Astar" },
    { symbol: "BLUR", name: "Blur" },
    { symbol: "MASK", name: "Mask Network" },
    { symbol: "LDO", name: "Lido DAO" },
    { symbol: "RPL", name: "Rocket Pool" },
    { symbol: "SSV", name: "SSV Network" },
    { symbol: "PENDLE", name: "Pendle" },
    { symbol: "JUP", name: "Jupiter" },
    { symbol: "W", name: "Wormhole" },
    { symbol: "STRK", name: "Starknet" },
    { symbol: "ZK", name: "zkSync" },
    { symbol: "PIXEL", name: "Pixels" },
    { symbol: "PORTAL", name: "Portal" },
    { symbol: "PDA", name: "PlayDapp" },
    { symbol: "MBL", name: "MovieBloc" },
    { symbol: "HIVE", name: "Hive" },
    { symbol: "MED", name: "MediBloc" },
    { symbol: "CBK", name: "Cobak Token" },
    { symbol: "META", name: "Metadium" },
    { symbol: "WEMIX", name: "WEMIX" },
    { symbol: "BORA", name: "BORA" },
    { symbol: "XEC", name: "eCash" },
    { symbol: "LSK", name: "Lisk" },
    { symbol: "POWR", name: "Powerledger" },
    { symbol: "ELF", name: "aelf" },
    { symbol: "ARK", name: "Ark" },
    { symbol: "STORJ", name: "Storj" },
    { symbol: "GLM", name: "Golem" },
    { symbol: "GAS", name: "Gas" },
    { symbol: "NEO", name: "NEO" },
    { symbol: "IOTA", name: "IOTA" },
    { symbol: "XTZ", name: "Tezos" },
    { symbol: "EOS", name: "EOS" },
    { symbol: "BSV", name: "Bitcoin SV" },
    { symbol: "BTG", name: "Bitcoin Gold" }
];

window.OcdCoins = OcdCoins;
console.log("✅ OcdCoins.js 로드 완료! 총 " + OcdCoins.length + "개 코인");
